/**
 * mutation variables which is used inside vuex store
 */

export const REFRESH_USER_INFO = 'REFRESH_USER_INFO';
export const REFRESH_EXPIRE_INFO = 'REFRESH_EXPIRE_INFO';
export const REFRESH_PROMPT_MESSAGE = 'REFRESH_PROMPT_MESSAGE';
export const SAVE_LAST_VISIT = 'SAVE_LAST_VISIT';


export const REFRESH_CLIENT_LIST = 'REFRESH_CLIENT_LIST';
export const REFRESH_CLIENTS_BY_PAGE = 'REFRESH_CLIENTS_BY_PAGE';
export const CREATE_CLIENT = 'CREATE_CLIENT';
export const REFRESH_USER_LIST = 'REFRESH_USER_LIST';
export const REFRESH_USERS_BY_PAGE = 'REFRESH_USERS_BY_PAGE';
export const REFRESH_ACCESS_TOKEN_LIST = 'REFRESH_ACCESS_TOKEN_LIST';
export const REFRESH_ACCESS_TOKENS_BY_PAGE = 'REFRESH_ACCESS_TOKENS_BY_PAGE';
export const REFRESH_REFRESH_TOKEN_LIST = 'REFRESH_REFRESH_TOKEN_LIST';
export const REFRESH_REFRESH_TOKENS_BY_PAGE = 'REFRESH_REFRESH_TOKENS_BY_PAGE';
export const REFRESH_AUDIT_LOGS_BY_PAGE = 'REFRESH_AUDIT_LOGS_BY_PAGE';

export const REFRESH_MY_CLIENTS = "REFRESH_MY_CLIENTS";
export const REFRESH_MY_SESSIONS = "REFRESH_MY_SESSIONS";
export const REFRESH_SESSIONS_BY_PAGE = "REFRESH_SESSIONS_BY_PAGE";
export const REFRESH_AUTH_CODE_LIST = "REFRESH_AUTH_CODE_LIST";
export const REFRESH_AUTH_CODES_BY_PAGE = "REFRESH_AUTH_CODES_BY_PAGE";
export const REFRESH_MY_AUTH_CODES = "REFRESH_MY_AUTH_CODES";
export const REFRESH_MY_ACCESS_TOKENS = "REFRESH_MY_ACCESS_TOKENS";
export const REFRESH_MY_REFRESH_TOKENS = "REFRESH_MY_REFRESH_TOKENS";

export const REFRESH_CLIENT_VALID_STATUS = "REFRESH_CLIENT_VALID_STATUS";
export const REFRESH_AUTH_CODE = "REFRESH_AUTH_CODE";
